#-------------------------------
# General Site Settings
baseURL = "http://goseren.com"
languageCode = "en-us"
title = "Seren"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 6


[params]
  logo = "/images/icon.png" # You can add own logo. For example "/images/logo.png".
  description = "Seren: AI Chat Diary"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Main Menu
[menu]

      # Footer Menu
      [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      identifier = "status"
      name = "Service status"
      url = "https://status.goseren.com/status/seren"
      weight = 4

      [[menu.footer]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/privacy/"
      weight = 5



  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Seren: AI Chat Journal"
    author__bio = ""
    author__avatar = "/images/icon.png"

  # Social Links

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://instagram.com/go_seren"


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "Interactive Self-Reflection"
    hero__description = "Discover the art of modern journaling, where each check-in is amplified by AI's intuitive understanting, bringing you closer to your inner self."
    hero__image = "/images/phone.png"

#-------------------------------
# Features Settings
[params.features]
  enable = true
    [[params.features.list]]
    title = "Let AI guide your journey"
    description = "Dictate thoughts directly, effortlessly transcribed. AI will help you explore your thoughts and emotions more deeply."
    image = "/images/feature3.png"

  [[params.features.list]]
    title = "Beyond One Voice"
    description = "Engage with diverse facets of your thoughts and emotions. They will help you uncover new insights."
    image = "/images/feature1.png"

  [[params.features.list]]
    title = "Forever Privacy First"
    description = "A secure space. All your check ins and conversations are safely encrypted and never shared. Your thoughts remain your own, secure and private."
    image = "/images/feature2.png"




  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = false


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = false
    projects__title= "Latest works"
    projects__description= "I shows only the best websites and portfolios built completely with passion, simplicity & creativity!"


#-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial__title = "What do users say"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Natasha"
    designation = "Amsterdam"
    content = "I was journaling on paper and didn't really want to do it on my phone but after some time, it's actually so nice!"

  [[params.testimonial_item]]
    name = "Henny"
    designation = "Bali"
    content = "Wasn't sure what to expect, but this app's kinda become my daily de-stress ritual. I just talk to it and it actually gives me good feedback"

  [[params.testimonial_item]]
    name = "Clément"
    designation = "Paris"
    content = "It's kinda fun seeing what the AI comes back with, not half bad."

  [[params.testimonial_item]]
    name = "Sandra"
    designation = "Barcelona"
    content = "It's cool to chat with your past self :)"

  [[params.testimonial_item]]
    name = "Micaela"
    designation = "Porto Alegre"
    content = "I don't journal often, but when I do it's useful and helps me relax!"

  [[params.testimonial_item]]
    name = "Killian"
    designation = "Bayonne"
    content = "Great for my introvert days 🥺"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = false
    blog__title = "Recent Posts"
    blog__description = ""


  #-------------------------------
  # Gallery Footer Settings
  [params.gallery]
    enable = false


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "albert@goseren.com" # Add your form_id

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
